# Generated by Django 4.2 on 2024-02-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='lesson',
            field=models.ManyToManyField(to='testsite.lesson'),
        ),
    ]
