# Generated by Django 4.2 on 2024-02-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0003_alter_user_purchased_products'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='lesson',
            new_name='lessons',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
