# Generated by Django 4.2 on 2024-02-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0005_rename_lessons_product_included_lessons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='purchased_products',
        ),
        migrations.AddField(
            model_name='user',
            name='purchased_products',
            field=models.ManyToManyField(blank=True, to='testsite.product'),
        ),
    ]
