# Generated by Django 4.2 on 2024-02-29 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0007_remove_group_product_product_included_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='included_groups',
        ),
        migrations.AddField(
            model_name='group',
            name='to_product',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='testsite.product'),
            preserve_default=False,
        ),
    ]
