# Generated by Django 4.2 on 2024-02-29 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0010_alter_group_to_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='group_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='lesson_name',
            new_name='name',
        ),
    ]
