# Generated by Django 4.2 on 2024-02-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testsite', '0014_remove_profile_group_group_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, to='testsite.group'),
        ),
    ]
